"""baseline

Revision ID: 4b698ac48d60
Revises:
Create Date: 2026-09-23 10:15:50.800221

Autogenerated against an empty database (never against the already-built
dev database -- autogenerate diffs the target database's current schema
against the models, so running it against a database that already has
these tables finds nothing different and silently produces an empty
`upgrade()`, confirmed by doing so). The four `op.create_table` calls and
the index below are Alembic's own output, unedited.

The trigger and the "Uncategorised" bucket row are added by hand: they are
not SQLAlchemy-mapped constructs, so autogenerate cannot see them, but
`app/db/migrate_db.py` is guarded off once `alembic_version` exists (see its
reset_database()), so this migration is now the only thing that puts them
on a fresh database. Their SQL is written out below with the ids already
resolved, rather than imported from migrate_db.py: a migration is a frozen
record of what a database was given, so a later edit to the bucket id or the
trigger body must arrive as a new revision, not by silently changing this one.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

SEED_BUCKET_SQL = """
INSERT INTO main_categories (id, slug, name, position)
     VALUES (1, 'uncategorised', 'Uncategorised', 0);
INSERT INTO sub_categories (id, main_category_id, slug, name, position)
     VALUES (1, 1,
             'uncategorised', 'Uncategorised', 0);
SELECT setval('main_categories_id_seq', (SELECT max(id) FROM main_categories));
SELECT setval('sub_categories_id_seq',  (SELECT max(id) FROM sub_categories));
"""

CREATE_REFILE_TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION refile_items_to_uncategorised() RETURNS trigger AS $$
BEGIN
    IF OLD.id = 1 THEN
        RAISE EXCEPTION
            'the "Uncategorised" sub-category cannot be deleted: it is where documents from deleted sub-categories are refiled to';
    END IF;
    UPDATE items
       SET sub_category_id = 1
     WHERE sub_category_id = OLD.id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER refile_items_before_sub_category_delete
    BEFORE DELETE ON sub_categories
    FOR EACH ROW EXECUTE FUNCTION refile_items_to_uncategorised();
"""

# revision identifiers, used by Alembic.
revision: str = '4b698ac48d60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('ecocrop_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecocrop_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('main_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sub_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_category_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['main_category_id'], ['main_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('main_category_id', 'slug')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_category_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('read_directly', sa.Boolean(), nullable=False),
    sa.Column('via', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('licence_note', sa.Text(), nullable=True),
    sa.CheckConstraint("NOT (read_directly AND coalesce(btrim(via), '') <> '')", name='read_directly_excludes_via'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_items_crop_id_topic', 'items', ['crop_id', 'topic'], unique=False)
    # ### end Alembic commands ###

    # Hand-added: not autogenerated, see the module docstring.
    op.execute(SEED_BUCKET_SQL)
    op.execute(CREATE_REFILE_TRIGGER_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    # No explicit undo for the bucket row or the trigger: dropping
    # sub_categories below removes both (a trigger cannot outlive its
    # table). refile_items_to_uncategorised() itself is a standalone
    # function, not a table, so it is left behind -- exactly what
    # migrate_db.py's own comment says drop_all() always did.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_crop_id_topic', table_name='items')
    op.drop_table('items')
    op.drop_table('sub_categories')
    op.drop_table('main_categories')
    op.drop_table('crops')
    # ### end Alembic commands ###
