"""members

Revision ID: 82c1cba61444
Revises: c29b352836f5
Create Date: 2026-10-04 10:35:32.353662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c1cba61444'
down_revision: Union[str, Sequence[str], None] = 'c29b352836f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('tokens_used_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tokens_budget_daily', sa.Integer(), server_default=sa.text('20000'), nullable=False),
    sa.Column('budget_window_start', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.CheckConstraint('tokens_budget_daily >= 0', name='tokens_budget_daily_non_negative'),
    sa.CheckConstraint('tokens_used_today >= 0', name='tokens_used_today_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
