"""item_chunks embedded_at

Revision ID: c29b352836f5
Revises: edc12af29a80
Create Date: 2026-10-01 20:08:16.959353

Autogenerated against cms_test at edc12af29a80, where item_chunks existed
without this column. The add_column below is Alembic's own output, unedited.

`created_at` is when a chunk row was first inserted; `embedded_at` is when its
current vector was produced, reset by scripts/reindex.py on every re-embed.

The backfill is added by hand. add_column alone would fill existing rows from
the server default -- the time this migration runs, when no vector was
produced. The backfill copies created_at instead: the existing rows were
embedded once and never re-embedded, so created_at is their embed time. (A
row that had been re-embedded would get its first embed time, not its last;
there is no record of the later one to copy.)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29b352836f5'
down_revision: Union[str, Sequence[str], None] = 'edc12af29a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_chunks', sa.Column('embedded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

    # Hand-added: see the module docstring.
    op.execute("UPDATE item_chunks SET embedded_at = created_at")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_chunks', 'embedded_at')
    # ### end Alembic commands ###
