"""item_chunks

Revision ID: d9972992c8ca
Revises: 4b698ac48d60
Create Date: 2026-10-01 15:21:47.849188

Autogenerated against cms_test at 4b698ac48d60, a database without this
table, so `upgrade()` is non-empty. The body below is Alembic's own output,
unedited; the one hand edit is `import pgvector.sqlalchemy`, which
autogenerate omits while still referencing `pgvector.sqlalchemy.vector.VECTOR`
-- without it, `upgrade()` raises NameError: name 'pgvector' is not defined.

No vector index, deliberately: see docs/design-notes.md, "No vector index yet".
"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy  # hand-added, see the module docstring
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9972992c8ca'
down_revision: Union[str, Sequence[str], None] = '4b698ac48d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'chunk_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_chunks')
    # ### end Alembic commands ###
